[feature] Support both full verification and quick count.
adiom-data/dsync pull request #82
Opened 2024-10-04 20:12 UTC by adiom-mark

Supports a new --verify-quick-count flag.
Default verify does a full verification.

Full verification currently does an xor across a hash of each bson document. Currently we don't dissect the raw bson. Will need to explore if it is necessary as it will definitely slow things down. Currently it seems to work.

2024-10-04 20:19 UTC, adiom-mark commented
The situation where it fails is if I "unset" a field and reset it to the same value because that field gets reordered to the end.

If I edit a field and edit it again it is fine.

2024-10-06 00:10 UTC, alex-thc commented on connectors/mongo/integrity.go
> +		c, err := collection.CountDocuments(mc.Ctx, filter)
Need to use the estimated count instead:https://www.mongodb.com/docs/manual/reference/method/db.collection.estimatedDocumentCount/

CountDocuments() does a full index scan

2024-10-06 01:01 UTC, alex-thc requested changes
This is solid! Took 8 minutes on the large test instance with 16 verification threads. I also propose 
1) changing --parallel-integrity-check to --parallel-integrity-check-workers or something, otherwise it sounds like a boolean param
2) set the load-level-inferred value to btc (equal to the number of initial copy workers)
3) documentation :)

2024-10-06 01:05 UTC, alex-thc approved these changes

2024-10-06 02:51 UTC, merged